name: CommandWhitelist
version: '${version}'
main: me.leonrobi.commandwhitelist.CommandWhitelist
api-version: '1.20'
folia-supported: true

commands:
  cwreload:
    permission: commandwhitelist.cwreload